/**
 * GenericCms
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { EntityDescriptor } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface EntityServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param name 
     */
    entityDescriptorNameGet(name: string, extraHttpRequestParams?: any): Observable<EntityDescriptor>;

    /**
     * 
     * 
     */
    entityEntitiesGet(extraHttpRequestParams?: any): Observable<Array<string>>;

    /**
     * 
     * 
     * @param name 
     * @param operationName 
     * @param requestBody 
     */
    entityExecuteOperationNameOperationNamePost(name: string, operationName: string, requestBody?: { [key: string]: any; }, extraHttpRequestParams?: any): Observable<Array<any>>;

    /**
     * 
     * 
     * @param name 
     */
    entityNameGet(name: string, extraHttpRequestParams?: any): Observable<Array<any>>;

    /**
     * 
     * 
     * @param name 
     * @param id 
     */
    entityNameIdDelete(name: string, id: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param name 
     * @param id 
     */
    entityNameIdGet(name: string, id: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param name 
     * @param id 
     * @param requestBody 
     */
    entityNameIdPut(name: string, id: string, requestBody?: { [key: string]: any; }, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param name 
     * @param requestBody 
     */
    entityNamePost(name: string, requestBody?: { [key: string]: any; }, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param name 
     * @param requestBody 
     */
    entityQueryNamePost(name: string, requestBody?: { [key: string]: any; }, extraHttpRequestParams?: any): Observable<Array<any>>;

}
