/**
 * GenericCms
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DynamicProperty } from './dynamicProperty';


export interface OperationDescriptor { 
    name?: string | null;
    inputModel?: Array<DynamicProperty> | null;
    outputModel?: Array<DynamicProperty> | null;
}

